name: Build

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: NPM Install
        run: npm install

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
          echo "Docker Scout installed at $(realpath ~/.docker/cli-plugins/docker-scout)"

      - name: Docker Scout Scan
        run: |
          ~/.docker/cli-plugins/docker-scout quickview fs://.
          ~/.docker/cli-plugins/docker-scout cves fs://.

      - name: Docker Build and Push
        run: |
          docker build -t myntra .
          docker tag myntra rasota352/myntra:latest
          docker push rasota352/myntra:latest
        env:
          DOCKER_CLI_ACI: 1

      - name: Docker Scout Image Scan
        run: |
          ~/.docker/cli-plugins/docker-scout quickview rasota352/myntra:latest
          ~/.docker/cli-plugins/docker-scout cves rasota352/myntra:latest

  deploy:
   needs: build-analyze-scan   
   runs-on: [self-hosted]
   steps:
      - name: docker pull image
        run: docker pull rasota352/myntra:latest

      - name: Deploy to container
        run: docker rm -f game || true
        run: docker run -d --name game -p 3000:3000 rasota352/myntra:latest

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to kubernetes
        run: kubectl apply -f deployment-service.yml
