name: Build

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Specify the version of Node.js you want to install

      - name: NPM Install
        run: npm install

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Scout Scan
        run: |
          docker-scout quickview fs://.
          docker-scout cves fs://.

      - name: Docker Build and Push
        run: |
          docker build -t myntra .
          docker tag myntra rasota352/myntra:latest
          docker push rasota352/myntra:latest
        env:
          DOCKER_CLI_ACI: 1

      - name: Docker Scout Image Scan
        run: |
          docker-scout quickview rasota352/myntra:latest
          docker-scout cves rasota352/myntra:latest
